create table owner(
    owner_id int8 generated by default as identity,
    driver_license varchar(255) unique ,
    owner_name varchar(255),
    owner_patronymic varchar(255),
    owner_surname varchar(255),
    primary key (owner_id));

INSERT INTO owner(owner_name, owner_patronymic, owner_surname, driver_license)
VALUES ('Alexey', 'Mihaylovich', 'Dulov', 'YH543UVF'),
       ('Mihail', 'Petrovich', 'Zabolotnyi', 'BS710JJQ'),
       ('Ivan', 'Nikolaevich', 'Topolev', 'GQ901HTQ'),
       ('Sergey', 'Alexeevich', 'Laptev', 'BG052LQA'),
       ('Nikita', 'Ivanovich', 'Rebrov', 'OQ110NAR'),
       ('Petr', 'Milaylovich', 'Kisov', 'LQ051BAR'),
       ('Lubov', 'Viktorovna', 'Mamonova', 'NS660LZV'),
       ('Alena', 'Nikolaevna', 'Ponikarova', 'NN667MWE');

create table car(
    car_id int8 generated by default as identity,
    brand varchar(255),
    model varchar(255),
    number_car varchar(255),
    vin_number varchar(255),
    year_issue int4,
    owner_id int8,
    primary key (car_id));

INSERT INTO car(brand, model, year_issue, vin_number, number_car, owner_id)
VALUES ('Toyota', 'Crown', 1978, '65YHG872TGR', 'T791OH', 1),
       ('BWM', 'X5', 2016, '29KUH713UOC', 'H052UB', 5),
       ('Honda', 'CR-V', 2019, '92TNX026QPB', 'N266PQ', 8),
       ('Lexus', 'IS200', 2020, '45UQT682OQC', 'B027HQ', 3),
       ('Vaz', '2114', 1998, '90YFG116OPT', 'G102OL', 1),
       ('Porsche', '911', 2018, '53YVB562UGX', 'Z775HD', 5),
       ('Mercedes', 'CLS', 2021, '87VSP055ZYS', 'J050AS', 4),
       ('Renault', 'Logan', 2007, '27YWB551LAQ', 'M913CQ', 6),
       ('Skoda', 'Rapid', 2011, '02HAM820ZQP', 'HB780PS', 7),
       ('Chevrolet', 'Cruze', 2012, '75UTG077VQA', 'D053VX', 3);